### ISSUE TITLE
Estructura de archivos del repositorio incorrecta

### ISSUE THREAD

**Issue by pposca** [DavidValles90/DAW2-M9#1]
Hola,

La estructura no es correcta. Falta la carpeta UF1.

**Comment by DavidValles90** [comment]
Hola,

He visto y seguido los pasos del video que colgaste en el classroom pero no entiendo como funciona...

En el momento de usar la terminal de comandos ciertas instrucciones me dan error y no se como continuar,

Estoy dando palos de ciego intentando averiguar como funciona pero creo que la estoy liando mas que otra cosa,

Si puedes echarme una mano te lo agradecería,

Gracias.

**Comment by pposca** [comment]
Hola,

Ves haciendo el proyecto en tu ordenador y el próximo día de clase te ayudo, no te preocupes.
